### PR TITLE
Fix removing ? and # characters

### LINKED ISSUE #17: `?` or `#` query start not working (either documentation, JsBin or the source code is not correct)
The Documentation : https://canjs.com/doc/can-deparam.html states that deparam should be able to handle queries starting with `?` or `#`.
When testing this with the JsBin provided on the page it becomes clear that it doesn't (at least not the code run by JsBin.
The unit tests written also don't check for this behavior.

Either the documentation should be updated that this doesn't work (or just not mention it),
or the code should be updated to support this.

### PR DESCRIPTION
**Pull request by cherifGsoul**
Fixes #17 

This removes `?` and `#` characters from parameters:
`deparam("?foo=bar&number=1234"); // -> {"foo" : "bar", "number": 1234}`
`deparam("#foo[]=bar&foo[]=baz"); // -> '{"foo" : ["bar", "baz"]}`

The fix checks if the first character is `?` or `#`with`str.charAt(0)` and removes it with `str.substr(1, str.length);`

### CODE REVIEW

File: can-deparam.js [hunk 1]
```diff
@@ -42,6 +42,9 @@ var digitTest = /^\d+$/,
 	paramTest = /([^?#]*)(#.*)?$/,
 	entityRegex = /%([^0-9a-f][0-9a-f]|[0-9a-f][^0-9a-f]|[^0-9a-f][^0-9a-f])/i,
 	prep = function (str) {
+		if (str.charAt(0) === "#" || str.charAt(0) === "?") {
```
Comment (justinbmeyer) [inline can-deparam.js]: Another way to write this might be ...

between `entityRegex ` and `prep` create:

```
startChars = {"#": true,"?": true}
``

Then use that like this:

```
if (startChars[str.charAt(0)] === true) {
  str = str.substr(1); 
}
```

The 2nd argument isn't needed

**Review by phillipskevin — APPROVED** [review]
